import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/navigation'
import styles from '../styles/Index.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ILHANCAN RODOPLU</title>
        <style>{'body { background-color: pink; }'}</style>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <div className={styles.title}>
      <h1>ILHANCAN RODOPLU</h1>
      </div>
    </div>
    
  )
}
