import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Song.module.css'

export default function Song() {
  return (
    <div className={styles.container}>
      <Head>
        <style>{'body { background-color: black; }'}</style>
        <title>ILHANCAN RODOPLU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.songContent}>
      <h1>Song</h1>
      </div>
    </div>
  )
}
