import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Song.module.css";
import SongImage from "../components/SongImage";
import Lyrics from "../components/Lyrics";
import Link from "next/link";
import Button from "../components/Button";
import AudioPlayer from "../components/AudioPlayer";

export default function Song() {
  return (
    <div className={styles.container}>
      <Head>
        <style>{"body { background-color: black; }"}</style>
        <title>ILHANCAN RODOPLU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SongImage style={{ right: 0 }} />
      <div className={styles.songContent}>
        <h1>Song</h1>
        <AudioPlayer src={"/audio/audio-1.wav"} />
        <Link href="/" passHref>
          <Button text="Back" />
        </Link>
        <Lyrics />
      </div>
    </div>
  );
}
